---

- hosts: all
  become: true
  tasks:
  - name: Update repository index
    ansible.builtin.apt:
      update_cache: yes
  
  - name: Install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: add php support for apache
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
