--- 
- hosts: cloud_servers
  pre_tasks:
    - name: Install Updates on all Ubuntu Servers
      ansible.builtin.apt:
        update_cache: yes 
      when: ansible_distribution == "Ubuntu"

    - name: Install Updates on all Amazon Servers
      ansible.builtin.yum:
        update_cache: yes
      when: ansible_distribution == "Amazon"

  tasks:
   - name: Install Latest Version of Nginx on Ubuntu
     ansible.builtin.apt:
        name: nginx 
        state: latest
     when: ansible_distribution == "Ubuntu"

   - name: Install Latest Version of Nginx on Amazon Linux
     ansible.builtin.yum:
        name: nginx 
        state: latest 
     when: ansible_distribution == "Amazon"